---
- name: restart sensu server
  service: name={{ item }} state=restarted enabled=yes
  with_items:
    - sensu-server
    - sensu-api
    - uchiwa

- name: restart uchiwa
  service: name={{ item }} state=restarted enabled=yes
  with_items:
    - uchiwa
