---
 - name: ensure docker requirements
   apt: pkg={{ item }} state=latest install_recommends=no
   with_items: "{{ docker.dependencies }}"
   tags: [docker, packages]

 - name: ensure docker apt keys
   apt_key: keyserver=keyserver.ubuntu.com id={{ docker.apt.key }}
   tags: [docker, packages]

 - name: ensure docker repo
   apt_repository: repo='deb https://apt.dockerproject.org/repo {{ ansible_distribution|lower }}-{{ ansible_distribution_release|lower }} main' state=present update_cache=yes
   tags: [docker, packages]

 - name: ensure docker package
   apt: pkg={{ item }} state=latest install_recommends=no
   with_items:
     - docker-engine
   notify: restart docker
   tags: [docker, packages]
