---
 - name: ensure sysdig keys
   apt_key: data="{{ item }}" state=present
   with_file:
     - sysdig.gpg
   tags: sysdig

 - name: ensure sysdig repo
   apt_repository: repo="{{ item }}" state=present update_cache=yes
   with_items:
     - "deb http://download.draios.com/stable/deb stable-$(ARCH)/"
   tags: sysdig

 - name: ensure sysdig package
   apt: pkg={{ item }} state=latest install_recommends=no
   with_items:
     - sysdig
   tags: sysdig
