---
 - name: ensure openvpn package
   apt: pkg={{ item }} state=latest install_recommends=no
   with_items:
     - openvpn
   tags: 
     - openvpn-server
     - openvpn-client

 - name: ensure openvpn client configuration
   template: src={{ item }} dest=/etc/openvpn/client.conf mode=600
   with_first_found:
     - files:
       - "{{ openvpn.client_conf }}"
       - "{{ private_dir }}/files/openvpn/{{ ansible_fqdn }}-openvpn_client"
       - "{{ private_dir }}/files/openvpn/{{ ansible_hostname }}-openvpn_client"
       - "{{ private_dir }}/files/openvpn/{{ ansible_domain }}-openvpn_client"
   notify:
     - restart openvpn
   tags: 
     - openvpn-client