---
sensu:
  plugins: 
    - sensu-plugins-cpu-checks
    - sensu-plugins-disk-checks
    - sensu-plugins-dns
    - sensu-plugins-filesystem-checks
    - sensu-plugins-network-checks
    - sensu-plugins-ntp
    - sensu-plugins-process-checks

  embedded_ruby: "true"
  safe_mode: "false"
  checks:
    - check_cpu.json
    - check_cron.json
    - check_disk.json
    - check_dns.json
    - check_ssh.json
    - check_ntp.json
    - check_reboot.json
