---
sensu:
  plugins:
    url: https://github.com/sensu/sensu-community-plugins.git
    version: master
    path: /opt/sensu-community-plugins

  checks:
    - check_cpu.json
    - check_cron.json
    - check_disk.json
    - check_dns.json
    - check_ssh.json
    - check_ntp.json
    - check_reboot.json