---
 - name: ensure dns server
   action: apt pkg=$item state=latest install_recommends=no
   with_items:
     - pdns-server
     #- pdns-recursor
   tags: dns-server

 - name: ensure dns records
   template: src=pdns.local dest=/etc/powerdns/pdns.d/pdns.local owner=root group=root mode=0600
   notify: restart dns server
   tags: dns-server

 - name: ensure dns records location
   action: file path=/etc/powerdns/bind/ owner=root group=root mode=0755 state=directory
   tags: dns-server

 - name: ensure dns internal records
   template: src=named.conf dest=/etc/powerdns/bind/named.conf owner=root group=root mode=0644
   notify: restart dns server
   tags: dns-server

 - name: ensure dns internal zone
   template: src=internal.zone dest=/etc/powerdns/bind/${dns.domain}.zone owner=root group=root mode=0644
   notify: restart dns server
   tags: dns-server
