language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl
install:
  - pip install ansible
script:
  - ansible-playbook --version
  - sudo cp -r ./deployment/ /etc/ansible
  - echo localhost > /etc/ansible/hosts
  - ansible-playbook --syntax-check --list-tasks base_servers.yml
  - ansible-playbook --connection=local --sudo -vvvv base_servers.yml