---
- name: restart dns server
  service: name=pdns state=restarted

- name: reload dns server
  service: name=pdns state=reloaded

- name: restart recursive dns server
  service: name=pdns-recursor state=restarted
