---
influxdb:
  dependencies:
   - python-pycurl
   
  version: 0.6.5_amd64
  hash: ea12d310ac951013ca4e959ee5b4cc961b7f5a2b80baebd89e98ad36c16cb29e
  
  bind_address: 127.0.0.1
  input_plugins:
   graphite:
    enabled: "true"
    port: 2003
    database: graphite