---
 - name: ensure monitoring requirements
   action: apt pkg=$item state=latest install_recommends=no
   with_items:
     - python-pycurl
   tags: monitoring

 - name: ensure monitoring client keys
   action: apt_key data="{{ item }}" state=present
   with_file:
     - sensu.gpg
   tags: monitoring

 - name: ensure monitoring repo
   action: apt_repository repo='deb http://repos.sensuapp.org/apt sensu main' state=present update_cache=yes
   tags: monitoring
   
 - name: ensure monitoring package
   action: apt pkg=$item state=latest install_recommends=no
   with_items:
     - sensu
     - git
   tags: monitoring

 # TODO: use executable in later ansible versions to specify the sensu gem binary
 #- name: ensure monitoring plugins
 #  gem: name=sensu-plugin state=latest
 #  tags: monitoring

 - name: ensure monitoring features installed
   action: git repo=https://github.com/sensu/sensu-community-plugins.git dest=/opt/sensu-community-plugins version=master update=yes depth=1
   tags: monitoring

 - name: ensure monitoring plugins installed
   action: file src=/opt/sensu-community-plugins/plugins dest=/etc/sensu/plugins/sensu-community-plugins owner=root group=root state=link
   tags: monitoring

 - name: ensure monitoring handlers installed
   action: file src=/opt/sensu-community-plugins/handlers dest=/etc/sensu/handlers/sensu-community-plugins owner=root group=root state=link
   tags: monitoring

 - name: ensure monitoring client configuration
   template: src=client.json dest=/etc/sensu/conf.d/client.json owner=root group=root mode=0644
   notify: restart monitoring
   tags: monitoring

 - name: ensure monitoring configuration
   template: src=config.json dest=/etc/sensu/config.json owner=root group=root mode=0644
   notify: restart monitoring
   tags: monitoring

 - name: ensure monitoring default
   template: src=default dest=/etc/default/sensu owner=root group=root mode=0644
   notify: restart monitoring
   tags: monitoring

