---
 - name: ensure sensu requirements
   apt: pkg={{ item }} state=latest install_recommends=no
   with_items:
     - python-pycurl
   tags: [sensu, packages]

 - name: ensure sensu client keys
   apt_key: data="{{ item }}" state=present
   with_file:
     - sensu.gpg
   tags: [sensu, packages]

 - name: ensure sensu repo
   apt_repository: repo='deb http://repositories.sensuapp.org/apt sensu main' state=present update_cache=yes
   tags: [sensu, packages]
   
 - name: ensure sensu package
   apt: pkg={{ item }} state=latest install_recommends=no
   with_items:
     - sensu
     - git
   tags: [sensu, packages]

 - name: ensure sensu plugins
   gem: name={{ item }} state=latest executable=/opt/sensu/embedded/bin/gem
   with_items: "{{ sensu.plugins }}"
   tags: [sensu, packages]

 - name: ensure sensu base configuration
   template: src=config.json dest=/etc/sensu/config.json owner=root group=root mode=0644
   notify: restart sensu client
   tags: sensu

 - name: ensure sensu configuration
   template: src={{ item }} dest=/etc/sensu/conf.d/{{ item }} owner=root group=root mode=0644
   with_items:
     - client.json
     - rabbitmq.json
   notify: restart sensu client
   tags: sensu

 - name: ensure sensu default
   template: src=default dest=/etc/default/sensu owner=root group=root mode=0644
   notify: restart sensu client
   tags: sensu
