---
 - name: ensure monitoring requirements
   apt: pkg={{ item }} state=latest install_recommends=no
   with_items:
     - python-pycurl
   tags: monitoring

 - name: ensure monitoring client keys
   apt_key: data="{{ item }}" state=present
   with_file:
     - sensu.gpg
   tags: monitoring

 - name: ensure monitoring repo
   apt_repository: repo='deb http://repos.sensuapp.org/apt sensu main' state=present update_cache=yes
   tags: monitoring
   
 - name: ensure monitoring package
   apt: pkg={{ item }} state=latest install_recommends=no
   with_items:
     - sensu
     - git
   tags: monitoring

 - name: ensure monitoring plugins
   gem: name=sensu-plugin state=latest executable=/opt/sensu/embedded/bin/gem
   tags: monitoring

 - name: ensure monitoring features installed
   git: repo={{ sensu.plugins.url }} dest={{ sensu.plugins.path }} version={{ sensu.plugins.version }} update=yes depth=1
   tags: monitoring

 - name: ensure monitoring plugins installed
   file: src={{ sensu.plugins.path }}/plugins dest=/etc/sensu/plugins/sensu-community-plugins owner=root group=root state=link
   tags: monitoring

 - name: ensure monitoring handlers installed
   file: src={{ sensu.plugins.path }}/handlers dest=/etc/sensu/handlers/sensu-community-plugins owner=root group=root state=link
   tags: monitoring

 - name: ensure monitoring configuration
   template: src={{ item }} dest=/etc/sensu/conf.d/{{ item }} owner=root group=root mode=0644
   with_items:
     - client.json
     - rabbitmq.json
   notify: restart monitoring
   tags: monitoring

 - name: ensure monitoring default
   template: src=default dest=/etc/default/sensu owner=root group=root mode=0644
   notify: restart monitoring
   tags: monitoring
