---
 - name: ensure grafana dependencies
   apt: pkg={{ item }} state=latest install_recommends=no
   with_items: "{{ grafana.dependencies }}"
   tags: grafana

 - name: ensure grafana keys
   apt_key: data="{{ item }}" state=present
   with_file:
     - grafana.gpg
   tags: [grafana, packages]

 - name: ensure grafana repo
   apt_repository: repo='deb https://packagecloud.io/grafana/stable/debian/ wheezy main' state=present update_cache=yes
   tags: [grafana, packages]

 - name: ensure grafana package
   apt: pkg={{ item }} state=latest install_recommends=no
   with_items:
     - grafana
   notify: restart grafana
   tags: [grafana, packages]

