---
 - name: ensure grafana dependencies
   apt: pkg={{ item }} state=latest install_recommends=no
   with_items: grafana.dependencies
   tags: grafana

 - name: ensure grafana location
   file: path={{ grafana.path }} owner=nginx group=root mode=0755 state=directory
   tags: grafana

 - name: ensure latest grafana
   git: repo={{ grafana.url }} dest={{ grafana.path }} version={{ grafana.version }} update=yes depth=1
   tags: grafana
