---
 - name: ensure logging
   action: apt pkg=$item state=latest install_recommends=no
   with_items:
     - rsyslog
   tags: logging

 - name: ensure logging configuration
   action: template src=50-default.conf dest=/etc/rsyslog.d/50-default.conf owner=root group=root mode=0644
   notify: restart logging
   tags: logging

