---
 - name: ensure ntp
   apt: pkg={{ item }} state=latest install_recommends=no
   with_items:
     - ntp
   tags: time

 - name: ensure localtime
   file: src=/usr/share/zoneinfo/{{ time.timezone }} path=/etc/localtime state=link owner=root group=root force=yes
   tags: time

 - name: ensure timezone
   copy: content={{ time.timezone }} dest=/etc/timezone
   notify: update timezone
   tags: time
