---
 - name: ensure ntp
   action: apt pkg=$item state=latest install_recommends=no
   with_items:
     - ntp
   tags: time

 - name: ensure localtime
   action: file src=/usr/share/zoneinfo/$time_timezone dest=/etc/localtime owner=root group=root state=link force=yes
   tags: time

 - name: ensure timezone
   copy: content=$time_timezone dest=/etc/timezone
   notify:
   - update timezone
   tags: time
