---
 - name: ensure diamond dependencies
   apt: pkg={{ item }} state=latest install_recommends=no
   with_items: "{{ diamond.dependencies }}"
   tags: [diamond, packages]

 - name: ensure diamond directory
   file: path={{ diamond.path }} group=root owner=root mode=0755 state=directory
   tags: [diamond, packages]

 - name: ensure diamond requirements
   template: src=requirements.txt dest={{ diamond.path }}/requirements.txt
   tags: [diamond, packages]

 - name: ensure diamond
   pip: requirements={{ diamond.path }}/requirements.txt virtualenv={{ diamond.path }}/venv state=latest
   notify: restart diamond
   tags: [diamond, packages]

 - name: ensure diamond user
   user: name=diamond comment="Diamond service account" system=yes home=/var/log/diamond shell=/usr/sbin/nologin
   notify: restart diamond
   tags: diamond

 - name: ensure diamond configuration directory
   file: path=/etc/diamond/collectors group=root owner=root mode=0755 state=directory
   tags: diamond

 - name: ensure diamond configuration
   template: src=diamond.conf dest=/etc/diamond/diamond.conf owner=root group=root mode=0644
   notify: restart diamond
   tags: diamond

 - name: ensure diamond collectors
   command: creates="/etc/diamond/collectors/{{ item }}.conf" cp /opt/diamond/venv/etc/diamond/collectors/{{ item }}.conf /etc/diamond/collectors/{{ item }}.conf
   with_items: "{{ diamond.collectors }}"
   notify: restart diamond
   tags: diamond

 - name: ensure diamond collectors enabled
   lineinfile: dest=/etc/diamond/collectors/{{ item }}.conf
               regexp='^enabled'
               line='enabled = true'
               backrefs=yes
               state=present
   with_items: diamond.collectors
   notify: restart diamond
   tags: diamond
   
 - name: ensure diamond upstart
   template: src=diamond.init dest=/etc/init/diamond.conf owner=root group=root mode=0644
   notify: restart diamond
   tags: diamond
