---
logstash:
  version: 1.3.2
  hash: 6a6a6e55efd14a182560af8143883eace1936afb11d59d0c35ce4ed5a5576a18
  path: /opt/logstash
  initial_java_heap: 256m
  maximum_java_heap: 256m
  dependencies:
    - openjdk-7-jdk
    - openjdk-7-jre
