---
logstash:
  url: https://download.elasticsearch.org/logstash/logstash
  jar: logstash-1.3.1-flatjar.jar
  dir: /opt/logstash
  dependencies:
    - openjdk-7-jdk
    - openjdk-7-jre

kibana:
  url: https://github.com/elasticsearch/kibana/
  dir: /var/www/
