---
 - name: ensure google-authenticator dependencies
   apt: pkg={{ item }} state=latest install_recommends=no
   with_items:
    - ${google-authenticator.dependencies}
   tags: google-authenticator
