---
 - name: ensure elasticsearch requirements
   apt: pkg={{ item }} state=latest install_recommends=no
   with_items:
     - ${elasticsearch.dependencies}
   tags: elasticsearch

 - name: ensure elasticsearch keys
   apt_key: data="{{ item }}" state=present
   with_file:
     - elasticsearch.gpg
   tags: elasticsearch

 - name: ensure elasticsearch repo
   apt_repository: repo='deb http://packages.elasticsearch.org/elasticsearch/{{ elasticsearch.version }}/debian stable main' state=present update_cache=yes
   tags: elasticsearch

 - name: ensure elasticsearch package
   apt: pkg={{ item }} state=latest install_recommends=no
   with_items:
     - elasticsearch
   tags: elasticsearch

 - name: ensure elasticsearch plugins 
   command: /usr/share/elasticsearch/bin/plugin -install {{ item.name }} creates={{ item.creates }}
   with_items:
     - ${elasticsearch.plugins}
   tags: elasticsearch
