---
 - name: ensure shells
   action: apt pkg=$item state=latest install_recommends=no
   with_items:
     - zsh
     - bash
   tags: user

 - name: ensure terminal utilities
   action: apt pkg=$item state=latest install_recommends=no
   with_items:
     - tmux
     - screen
   tags: user

 - name: ensure editors
   action: apt pkg=$item state=latest install_recommends=no
   with_items:
     - nano
     - emacs
     - vim
   tags: user

 - name: ensure irc clients
   action: apt pkg=$item state=latest install_recommends=no
   with_items:
     - irssi
     - weechat-curses
   tags: user
   
 - name: ensure development tools
   action: apt pkg=$item state=latest install_recommends=no
   with_items:
     - build-essential
     - python-dev
     - git
     - subversion
     - mercurial
     - bzr
   tags: user

 - name: ensure user utlities
   action: apt pkg=$item state=latest install_recommends=no
   with_items:
     - unzip
     - unrar
     - finger
     - wget
     - curl
     - mutt
     - slrn
     - lynx
     - w3m
     - elinks
   tags: user

 - name: ensure firewall
   action: apt pkg=$item state=latest install_recommends=no
   with_items:
     - ufw
     - iptables
   tags: user

 - name: ensure hardening
   action: apt pkg=$item state=latest install_recommends=no
   with_items:
     - fail2ban
   tags: user

