---
 - name: ensure ansible dependencies
   apt: pkg={{ item }} state=latest install_recommends=no
   with_items: "{{ ansible.dependencies }}"
   tags: [ansible, packages]

 - name: ensure ansible directory
   file: path={{ ansible.path }} group=root owner=root mode=0755 state=directory
   tags: [ansible, packages]

 - name: ensure ansible requirements
   template: src=requirements.txt dest={{ ansible.path }}/requirements.txt
   tags: [ansible, packages]

 - name: ensure ansible
   pip: requirements={{ ansible.path }}/requirements.txt virtualenv={{ ansible.path }}/venv state=latest
   notify: restart ansible
   tags: [ansible, packages]
