---
influxdb:
  dependencies:
   - python-pycurl

  version: 0.8.5_amd64
  hash: 58ae034557e6a2886530577ab368ed2153b4e0a41bcfa57d8b15a9d5006f14d0

  bind_address: 127.0.0.1
  input_plugins:
   graphite:
    enabled: "true"
    port: 2003
    database: graphite