---
influxdb:
  dependencies:
   - python-pycurl

  version: 0.9.3_amd64
  hash: d82ffbb414722fd7e3154642c6a7a6c369db55a233f506e6cfe044f587eb28e2

  bind_address: 127.0.0.1
  input_plugins:
   graphite:
    enabled: "true"
    port: 2003
    database: graphite