---
- name: Run all playbooks
  hosts: all
  become: True
  become_method: sudo

  vars_files:
    - private_vars.yml

# upgrade all the servers
- include: upgrade_servers.yml

# setup the following servers before the base configuration
- include: dns_servers.yml
- include: mgmt_servers.yml
- include: ldap_servers.yml
- include: logging_servers.yml

# configure all the servers according to this
- include: base_servers.yml

# specific servers are now configured
- include: email_servers.yml
- include: irc_servers.yml
- include: www_servers.yml
