---
- name: Upgrade all servers
  hosts: all
  sudo: True

  pre_tasks:
    - name: ensure package cache updated
      apt: update_cache=yes cache_valid_time=3600
      tags: upgrade

    - name: ensure packages upgraded
      apt: upgrade=safe
      tags: upgrade