---
- name: Upgrade all servers
  hosts: all
  sudo: True

  pre_tasks:
    - name: ensure package cache updated
      apt: update_cache=yes cache_valid_time=3600
      tags: upgrade

    - name: ensure packages upgraded
      apt: upgrade=dist
      tags: upgrade

    - name: ensure unused dependencies need to be removed
      command: apt-get --dry-run autoremove
      register: check_autoremove
      changed_when: False
      tags: upgrade

     - name: ensure unused dependencies removed
       command: apt-get -y --purge autoremove
       when: "'packages will be REMOVED' in check_autoremove.stdout"
       tags: upgrade

     - name: ensure unused packages need to be removed
       command: apt-get --dry-run autoclean
       register: check_autoclean
       changed_when: False
       tags: upgrade
	   
    - name: ensure unused packages removed
      command: apt-get -y autoclean
      when: "'Del ' in check_autoclean.stdout"
      tags: upgrade