---
elasticsearch:
  url: https://download.elasticsearch.org/elasticsearch/elasticsearch
  package: elasticsearch-0.90.9.deb
  hash: a349e700451be3c2e910a5cd05e3a6baaca8cabfde3cc93580f1b4b1db48316f
  dependencies:
   - openjdk-7-jre-headless
  plugins:
    - name: royrusso/elasticsearch-HQ
      creates: /usr/share/elasticsearch/plugins/HQ/_site/index.html
