---
elasticsearch:
  version: 2.x
  dependencies:
   - openjdk-7-jre-headless
   - python-pycurl

  plugins:
    - name: royrusso/elasticsearch-HQ
      creates: /usr/share/elasticsearch/plugins/hq/index.html

  cluster:
    name: elasticsearch
  bootstrap:
    mlockall: "true"
