---
elasticsearch:
  version: 0.90.10
  hash: 599a8ff133f0800bb58032f1bf4ec0b1746c307befb57c65ee9d32af9f407c04
  dependencies:
   - openjdk-7-jre-headless
  plugins:
    - name: royrusso/elasticsearch-HQ
      creates: /usr/share/elasticsearch/plugins/HQ/_site/index.html

  index:
    number_of_shards: 1
    number_of_replicas: 0

  discovery.zen.ping.multicast.enabled: "false"
