---
elasticsearch:
  url: https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.90.10.deb
  version: 0.90.10
  hash: 599a8ff133f0800bb58032f1bf4ec0b1746c307befb57c65ee9d32af9f407c04
  dependencies:
   - openjdk-7-jre-headless
  plugins:
    - name: royrusso/elasticsearch-HQ
      creates: /usr/share/elasticsearch/plugins/HQ/index.html
