---
 - name: ensure logging
   apt: pkg={{ item }} state=latest install_recommends=no
   with_items:
     - rsyslog
   tags: logging

 - name: ensure logging configuration
   template: src=rsyslog.conf dest=/etc/rsyslog.conf owner=root group=root mode=0644
   notify: restart logging
   tags: logging
 
 - name: ensure logging client configuration
   template: src=50-default.conf dest=/etc/rsyslog.d/50-default.conf owner=root group=root mode=0644
   notify: restart logging
   tags: logging

 - name: ensure logging remotely configuration
   template: src=100-remote.conf dest=/etc/rsyslog.d/100-remote.conf owner=root group=root mode=0644
   notify: restart logging
   tags: logging
