---
 - name: ensure rtorrent dependencies
   apt: pkg={{ item }} state=latest install_recommends=no
   with_items: "{{ rtorrent.dependencies }}"
   tags: [rtorrent, packages]

 - name: ensure rtorrent user
   user: name={{ rtorrent.user }} comment="rTorrent Service User" system=yes home={{ rtorrent.path }} shell=/bin/sh
   notify: restart rtorrent
   tags: rtorrent

 - name: ensure rtorrent directory
   file: path="{{ rtorrent.path }}/{{ item }}" group={{ rtorrent.group }} owner={{ rtorrent.user }} mode=0755 state=directory
   with_items:
    - incomplete
    - session
    - complete
   notify: restart rtorrent
   tags: rtorrent

 - name: ensure rtorrent watch section directory
   file: path="{{ rtorrent.path }}/watch/{{ item }}" group={{ rtorrent.group }} owner={{ rtorrent.user }} mode=0755 state=directory
   with_items: "{{ rtorrent.sections }}"
   notify: restart rtorrent
   tags: rtorrent

 - name: ensure rtorrent complete section directory
   file: path="{{ rtorrent.path }}/complete/{{ item }}" group={{ rtorrent.group }} owner={{ rtorrent.user }} mode=0755 state=directory
   with_items: "{{ rtorrent.sections }}"
   notify: restart rtorrent
   tags: rtorrent

 - name: ensure rtorrent configuration
   template: src=rtorrent.rc dest=/etc/rtorrent.rc owner=root group=root mode=0644
   notify: restart rtorrent
   tags: rtorrent

 - name: ensure rtorrent init
   template: src=rtorrent.init dest=/etc/init.d/rtorrent owner=root group=root mode=0755
   notify: restart rtorrent
   tags: rtorrent
