---
 - name: ensure sensu server package
   apt: pkg={{ item }} state=latest install_recommends=no
   with_items:
     - redis-server
   tags: sensu-server

 - name: ensure sensu server vhost
   rabbitmq_vhost: name={{ sensu.rabbitmq.vhost }} state=present
   tags: sensu-server

 - name: ensure sensu server user
   rabbitmq_user: user={{ sensu.rabbitmq.username }}
                  password={{ sensu.rabbitmq.password }}
                  vhost={{ sensu.rabbitmq.vhost }}
                  configure_priv=.*
                  read_priv=.*
                  write_priv=.*
                  state=present
   tags: sensu-server
   
 - name: ensure sensu server configuration
   template: src={{ item }} dest=/etc/sensu/conf.d/{{ item }} owner=root group=root mode=0644
   with_items:
     - api.json
     - handlers.json
     - rabbitmq.json
     - redis.json
   notify: restart sensu server
   tags: sensu-server

 - name: ensure sensu server checks
   template: src={{ item }} dest=/etc/sensu/conf.d/{{ item }} owner=root group=root mode=644
   with_items:
     - check_cpu.json
     - check_cron.json
     - check_disk.json
     - check_dns.json
     - check_ssh.json
   notify: restart sensu server
   tags: sensu-server

 - name: ensure uchiwa package
   apt: pkg={{ item }} state=latest install_recommends=no
   with_items:
     - uchiwa
   notify: restart uchiwa
   tags: sensu-server

 - name: ensure uchiwa configuration
   template: src={{ item }} dest=/etc/sensu/{{ item }} owner=root group=root mode=0644
   with_items:
     - uchiwa.json
   notify: restart uchiwa
   tags: sensu-server