---
 - name: ensure auditd package
   apt: pkg={{ item }} state=latest install_recommends=no
   with_items:
     - auditd
   tags: [auditd, packages]

 - name: ensure auditd rules
   template: src=audit.rules dest=/etc/audit/audit.rules owner=root group=root mode=0644
   notify: restart auditd
   tags: auditd
