---
 - name: ensure logstash dependencies
   action: apt pkg={{ item }} state=latest install_recommends=no
   with_items:
    - ${logstash.dependencies}
   tags: logstash

 - name: ensure logstash directory
   action: file path={{ logstash.path }} group=root owner=root mode=0755 state=directory
   tags: logstash

 - name: ensure logstash
   get_url: url={{ logstash.url }}/{{ logstash.jar }} dest={{ logstash.path }} mode=0644
   tags: logstash

 - name: ensure logstash init
   action: template src=init dest=/etc/init/logstash.conf owner=root group=root mode=0644
   tags: logstash