---
 - name: ensure logstash requirements
   apt: pkg={{ item }} state=latest install_recommends=no
   with_items: logstash.dependencies
   tags: logstash

 - name: ensure logstash keys
   apt_key: data="{{ item }}" state=present
   with_file:
     - logstash.gpg
   tags: logstash

 - name: ensure logstash repo
   apt_repository: repo='deb http://packages.elasticsearch.org/logstash/{{ logstash.version }}/debian stable main' state=present update_cache=yes
   tags: logstash

 - name: ensure logstash package
   apt: pkg={{ item }} state=latest install_recommends=no
   with_items:
     - logstash
   tags: logstash

 - name: ensure logstash default
   template: src=default dest=/etc/default/logstash owner=root group=root mode=0644
   notify: restart logstash
   tags: logstash

 - name: ensure logstash configuration
   template: src={{ item }} dest=/etc/logstash/conf.d/{{ item }} owner=root group=root mode=0644
   with_items:
     - 01_input.conf
     - 02_filter.conf
     - 03_output.conf
   notify: restart logstash
   tags: logstash
