---
 - name: ensure nodejs dependencies
   apt: pkg={{ item }} state=latest install_recommends=no
   with_items: "{{ nodejs.dependencies }}"
   tags: nodejs

 - name: ensure nodejs {{ nodejs.version }} installed
   shell: /usr/local/bin/node -v | grep -i {{ nodejs.version }}
   register: nodejs_version_exists
   ignore_errors: True
   changed_when: False
   tags: nodejs

 - name: ensure nodejs source
   git: repo={{ nodejs.url }} dest={{ nodejs.path }} version={{ nodejs.version }} update=yes depth=1
   when: nodejs_version_exists|failed
   tags: nodejs

 - name: ensure nodejs configured
   command: chdir="{{ nodejs.path }}" "{{ nodejs.path }}/configure"
   when: nodejs_version_exists|failed
   tags: nodejs

 - name: ensure nodejs make
   command: chdir="{{ nodejs.path }}" /usr/bin/make
   when: nodejs_version_exists|failed
   tags: nodejs

 - name: ensure nodejs make install
   command: chdir="{{ nodejs.path }}" /usr/bin/make install
   when: nodejs_version_exists|failed
   tags: nodejs
