---
 - name: ensure kibana location
   action: file path={{ kibana.path }} owner=www-data group=root mode=0755 state=directory
   tags: kibana

 - name: ensure latest kibana
   action: git repo={{ kibana.url }} dest=/var/www/ version=master update=yes depth=1
   tags: kibana

 - name: ensure kibana configuration
   action: template src=kibana.js dest=/var/www/src/config.js owner=root group=root mode=0644
   tags: kibana

