---
 - name: ensure language packs
   apt: pkg={{ item }} state=latest install_recommends=no
   with_items: language.dependencies
   tags: language

 - name: ensure system language
   template: src=locale dest=/etc/default/locale
   tags: language

