---
 - name: ensure rabbitmq requirements
   apt: pkg={{ item }} state=latest install_recommends=no
   with_items:
     - python-pycurl
   tags: rabbitmq

 - name: ensure rabbitmq keys
   apt_key: data="{{ item }}" state=present
   with_file:
     - rabbitmq.asc
   tags: rabbitmq

 - name: ensure rabbitmq repo
   apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main' state=present update_cache=yes
   tags: rabbitmq

 - name: ensure rabbitmq package
   apt: pkg={{ item }} state=latest install_recommends=no
   with_items:
     - rabbitmq-server
   notify: restart rabbitmq
   tags: rabbitmq

 - name: ensure rabbitmq plugins
   rabbitmq_plugin: names={{ item }} state=enabled
   with_items:
     - rabbitmq_management
   tags: rabbitmq

 # TODO: remove/change guest user account
